import json
import ollama  # local way to access llms without making api key

# cap body length so local model isn't stuck on 10KB newsletter bodies
MAX_BODY_CHARS = 1500
INPUT_FILE = "emails.jsonl"
OUTPUT_FILE = "responses.jsonl"

valid_responses = []

# instructions i want agent to follow
system_prompt = """You are a helpful assistant that summarizes emails.
Respond with only valid JSON in this exact shape:
{
  "summary": "<two sentence summary of the email>"
}
Do not include markdown code fences or any text outside the JSON object."""

# ollama expects string as input -> json is in string format
with open(INPUT_FILE, "r") as file:
  # remove any whitespace in json string; skip blank lines
  lines = [line.strip() for line in file if line.strip()]

total = len(lines)

for index, line in enumerate(lines, start=1):
  # .loads -> json string to python dictionary (one email per line)
  try:
    email = json.loads(line)
  except json.JSONDecodeError:
    print(f"[{index}/{total}] Skipped: input line is not valid JSON")
    continue

  # email_id comes from input — don't ask the LLM to copy it
  email_id = email.get("id")
  subject = email.get("subject", "")
  body = email.get("body", "")

  if not isinstance(email_id, str) or email_id.strip() == "":
    print(f"[{index}/{total}] Skipped: missing id")
    continue

  if len(body) > MAX_BODY_CHARS:
    body = body[:MAX_BODY_CHARS] + "..."

  # send only id, subject, and truncated body (not the whole raw jsonl line)
  user_prompt = json.dumps({
    "id": email_id,
    "subject": subject,
    "body": body,
  })

  print(f"[{index}/{total}] Summarizing: {subject[:60]!r}...", flush=True)

  # initialize client and generate response
  response = ollama.chat(
    model="qwen2.5:3b",  # model I want
    messages=[
      {"role": "system", "content": system_prompt},
      {"role": "user", "content": user_prompt},
    ],
  )

  # this is the actual response
  llm_response = response["message"]["content"].strip()

  # LLMs often wrap JSON in markdown fences — strip before json.loads
  if llm_response.startswith("```"):
    parts = llm_response.split("```")
    if len(parts) >= 2:
      llm_response = parts[1]
      if llm_response.startswith("json"):
        llm_response = llm_response[4:]
      llm_response = llm_response.strip()

  try:
    # will ensure that all llm responses are same format
    llm_response_dict = json.loads(llm_response)

    # valid checking to ensure required key was generated by llm
    summary = llm_response_dict.get("summary")

    # check that summary is a string
    if isinstance(summary, str):
      summary = summary.strip()

      # string is valid, now check for emptiness
      if summary != "":
        clean_response = {
          "email_id": email_id,  # from input, not from llm
          "summary": summary,
        }

        # this is list -> later gets converted to json format
        valid_responses.append(clean_response)
        print(f"[{index}/{total}] OK", flush=True)
      else:
        print(f"[{index}/{total}] Skipped: empty summary", flush=True)
    else:
      print(f"[{index}/{total}] Skipped: summary is not a string", flush=True)

  except json.JSONDecodeError:
    print(f"[{index}/{total}] Skipped: LLM response was not valid JSON", flush=True)

# with closes file after opening
with open(OUTPUT_FILE, "w") as file:

  # we have to add each email from list into file
  # file.write(json.dumps(r)) returns int of characters to add
  # json.dumps(r) + '\n' -> add newline before counting num characters
  for r in valid_responses:
    file.write(json.dumps(r) + "\n")  # .dumps -> python object to json string

print(f"Done: {len(valid_responses)}/{total} summaries written to {OUTPUT_FILE}")
